---
- name: Create Gitlab Project
  hosts: localhost
  vars:
    gitlab_project:
      - AAP2_Demos
      - Inv_Proj
      - Basic_Demo
  tasks:

    - name: Create Gitlab Project
      community.general.gitlab_project:
        api_url: https://git.lab.example.com/
        api_username: student
        api_password: Student@123
        name: "{{ item }}"
        validate_certs: "false"
        visibility: public
      loop: "{{ gitlab_project }}"
